# syntax=docker/dockerfile:1.7
# hadolint global ignore=SC2086,SC2016,DL3025
# LICENSE UPL 1.0
#
# Copyright (c) 2018, 2026 Oracle and/or its affiliates.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Containerfile for Oracle Database 26ai
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) LINUX.X64_2326100_db_home.zip
#     Download Oracle Database 26ai Enterprise Edition or Standard Edition 2 for Linux x64
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
# (2) apex-latest.zip
#     Download Oracle APEX (all languages) from
#     https://download.oracle.com/otn_software/apex/apex-latest.zip
# (3) ords-latest.zip
#     Download Oracle REST Data Services from
#     https://download.oracle.com/otn_software/java/ords/ords-latest.zip
#
# The image ships with Oracle APEX and ORDS. On the first container start APEX
# is installed into the PDB and ORDS is configured to serve it on port 8080
# (set APEX_ORDS_ENABLED=false to skip this and use the image as a plain DB).
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Containerfile
# Run: 
#      $ docker build -t oracle/database:23.26.0-${EDITION} .
#
# Pull base image
# ---------------
FROM oraclelinux:8 as base

# Labels
# ------
LABEL "provider"="Oracle"                                                           \
      "maintainer"="Oracle Database Container Team <container-team_ww@oracle.com>"  \
      "vendor"="Oracle Corporation"                                                 \
      "version"="23.26.0"                                                           \
      "release"="23.26.0"                                                           \
      "name"="Oracle Database 26ai"                                                 \
      "summary"="Oracle Database 26ai"                                              \
      "description"="Container Image for Oracle Database Server Release 26ai"       \
      "issues"="https://github.com/oracle/docker-images/issues"                     \
      "volume.data"="/opt/oracle/oradata"                                           \
      "volume.setup.location1"="/opt/oracle/scripts/setup"                          \
      "volume.setup.location2"="/docker-entrypoint-initdb.d/setup"                  \
      "volume.startup.location1"="/opt/oracle/scripts/startup"                      \
      "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"              \
      "port.listener"="1521"                                                        \
      "port.apex.ords"="8080"                                            

# Argument to control removal of components not needed after db software installation
ARG SLIMMING=true
ARG INSTALL_FILE_1="LINUX.X64_2326100_db_home.zip"
ARG APEX_INSTALL_FILE_1="apex-latest.zip"
ARG ORDS_INSTALL_FILE_1="ords-latest.zip"
ARG BACKUP_MODULE_URL=""
ARG BACKUP_MODULE_LOCAL_FILE=""

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/26ai/dbhome_1 \
    INSTALL_DIR=/opt/install \
    INSTALL_FILE_1=$INSTALL_FILE_1 \
    INSTALL_RSP="db_inst.rsp" \
    CONFIG_RSP="dbca.rsp.tmpl" \
    PWD_FILE="setPassword.sh" \
    RUN_FILE="runOracle.sh" \
    START_FILE="startDB.sh" \
    SHUTDOWN_FILE="shutDown.sh" \
    CREATE_DB_FILE="createDB.sh" \
    CREATE_OBSERVER_FILE="createObserver.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    INSTALL_DB_BINARIES_FILE="installDBBinaries.sh" \
    RELINK_BINARY_FILE="relinkOracleBinary.sh" \
    CONFIG_DG_PREREQS_FILE="configDataguardPrereqs.sh" \
    CLONEDB_OBJBACKUP="cloneDBObjBkup.sh" \
    MANAGE_TNS_ALIASES="manageTnsAliases.sh" \
    CONFIG_TCPS_FILE="configTcps.sh" \
    TDE_SECRET_UTILS_FILE="tdeSecretUtils.sh" \
    DECRYPT_PWD_FILE="decryptPassword.sh" \
    SCRIPT_BASE_DIR="/opt/oracle/scripts/base" \
    SLIMMING=$SLIMMING \
    ENABLE_ARCHIVELOG=false \
    ENABLE_FORCE_LOGGING=false \
    ARCHIVELOG_DIR_NAME=archive_logs \
    # To clone a database referred by PRIMARY_DB_CONN_STR
    CLONE_DB=false \
    # To create a standby database referred by PRIMARY_DB_CONN_STR
    STANDBY_DB=false \
    # Standby startup/health mode: READ_ONLY or MOUNTED
    STANDBY_OPEN_MODE=READ_ONLY \
    # Env var below should be in <HOST>:<PORT>/<SERVICE_NAME> format
    PRIMARY_DB_CONN_STR="" \
    # Optional primary source DB_NAME when it differs from the connect-string service name
    PRIMARY_DB_NAME="" \
    # For creating dataguard observer
    DG_OBSERVER_ONLY=false \
    DG_OBSERVER_NAME="" \
    CHECKPOINT_FILE_EXTN=".created" \
    WALLET_DIR=""

# Environment variables for the baked-in APEX/ORDS development platform.
# Use separate ENV so that $ORACLE_BASE gets substituted correctly.
# All APEX/ORDS passwords default to ORACLE_PWD and can be overridden with
# APEX_ADMIN_PWD, APEX_PUBLIC_USER_PWD, APEX_LISTENER_PWD and
# APEX_REST_PUBLIC_USER_PWD. Set APEX_ORDS_ENABLED=false at runtime to use
# the image as a plain database without APEX/ORDS.
ENV APEX_HOME=$ORACLE_BASE/apex \
    ORDS_HOME=$ORACLE_BASE/ords \
    ORDS_CONFIG=$ORACLE_BASE/oradata/ords-config \
    ORDS_PORT=8080 \
    APEX_ORDS_ENABLED=true \
    APEX_INSTALL_FILE_1=$APEX_INSTALL_FILE_1 \
    ORDS_INSTALL_FILE_1=$ORDS_INSTALL_FILE_1 \
    INSTALL_APEX_ORDS_FILE="installApexOrds.sh" \
    START_ORDS_FILE="startOrds.sh"

# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$ORACLE_HOME/python/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH \
    LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib \
    CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib

# Copy files needed during both installation and runtime
# -------------
COPY $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DIR/
COPY $RUN_FILE $START_FILE $SHUTDOWN_FILE $CREATE_DB_FILE $CREATE_OBSERVER_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $USER_SCRIPTS_FILE $RELINK_BINARY_FILE $CONFIG_DG_PREREQS_FILE $CONFIG_TCPS_FILE $TDE_SECRET_UTILS_FILE $DECRYPT_PWD_FILE $CLONEDB_OBJBACKUP $MANAGE_TNS_ALIASES $INSTALL_APEX_ORDS_FILE $START_ORDS_FILE ${SCRIPT_BASE_DIR}/

RUN chmod ug+x $INSTALL_DIR/*.sh && \
    mkdir -p "${SCRIPT_BASE_DIR}" && \
    chmod ug+x "${SCRIPT_BASE_DIR}"/*.sh && \
    printf '#!/bin/bash\nexec "%s/%s" "$@"\n' "$SCRIPT_BASE_DIR" "$RUN_FILE" > "$ORACLE_BASE/$RUN_FILE" && \
    chmod ug+x "$ORACLE_BASE/$RUN_FILE" && \
    for script in "$START_FILE" "$SHUTDOWN_FILE" "$CREATE_DB_FILE" "$CREATE_OBSERVER_FILE" "$PWD_FILE" "$CHECK_DB_FILE" "$USER_SCRIPTS_FILE" "$RELINK_BINARY_FILE" "$CONFIG_DG_PREREQS_FILE" "$CONFIG_TCPS_FILE" "$DECRYPT_PWD_FILE" "$CLONEDB_OBJBACKUP" "$MANAGE_TNS_ALIASES" "$INSTALL_APEX_ORDS_FILE" "$START_ORDS_FILE"; do \
      ln -sf "${SCRIPT_BASE_DIR}/$script" "$ORACLE_BASE/$script"; \
    done && \
    sync && \
    $INSTALL_DIR/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/$SETUP_LINUX_FILE && \
    rm -rf $INSTALL_DIR && \
    mkdir /licenses

RUN true


#############################################
# -------------------------------------------
# Start new stage for installing the database
# -------------------------------------------
#############################################

FROM base AS builder

ARG DB_EDITION

# Copy DB install file
COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/

# Install DB software binaries
USER oracle
RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION

# Copy APEX and ORDS install files
COPY --chown=oracle:dba $APEX_INSTALL_FILE_1 $ORDS_INSTALL_FILE_1 $INSTALL_DIR/

# Unzip APEX and ORDS into ORACLE_BASE so that they ship with the runtime layer
# (the final stage copies $ORACLE_BASE from this builder stage)
RUN mkdir -p $ORDS_HOME && \
    unzip -q $INSTALL_DIR/$APEX_INSTALL_FILE_1 -d $ORACLE_BASE && \
    unzip -q $INSTALL_DIR/$ORDS_INSTALL_FILE_1 -d $ORDS_HOME && \
    if [ ! -f $ORDS_HOME/bin/ords ] && [ -f $ORDS_HOME/ords/bin/ords ]; then \
      mv $ORDS_HOME/ords/* $ORDS_HOME/ && rmdir $ORDS_HOME/ords; \
    fi; \
    test -f $ORDS_HOME/bin/ords && \
    rm -f $INSTALL_DIR/$APEX_INSTALL_FILE_1 $INSTALL_DIR/$ORDS_INSTALL_FILE_1



#############################################
# -------------------------------------------
# Start new layer for database runtime
# -------------------------------------------
#############################################

FROM base

USER oracle
COPY --chown=oracle:dba --from=builder $ORACLE_BASE $ORACLE_BASE

USER root
RUN $ORACLE_BASE/oraInventory/orainstRoot.sh && \
    $ORACLE_HOME/root.sh

USER oracle
WORKDIR /home/oracle

# Add a bashrc file to capitalize ORACLE_SID in the environment
RUN echo 'ORACLE_SID=${ORACLE_SID:-ORCLCDB}; export ORACLE_SID=${ORACLE_SID^^}' > .bashrc

HEALTHCHECK --interval=1m --start-period=5m --timeout=30s \
   CMD "$SCRIPT_BASE_DIR/$CHECK_DB_FILE" >/dev/null || exit 1

EXPOSE 1521 8080

# Define default command to start Oracle Database. 
CMD exec $SCRIPT_BASE_DIR/$RUN_FILE
